import type { Metadata } from "next";
import "./globals.css";
import "./global.scss";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isDark = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={isDark ? "dark-mode" : ""}>
        {children}
      </body>
    </html>
  );
}
